// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxttlsreecsrrojexegy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dHRsc3JlZWNzcnJvamV4ZWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzUyNTYsImV4cCI6MjA2NTcxMTI1Nn0.WQ5fFogT3jnzkMpbPaeXiAfbjsSWMfFWX6UIzvfbbV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);